apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
  #username: root
  #password: cduc1978
  curso_url: msvc-cursos:8002
  application.yaml: |-
    config:
      texto: Ambiente por defecto.
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Ambiente de DEV.
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Ambiente de PROD.

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
  #username: postgres
  #password: cduc1978
  usuario_url: msvc-usuarios:8001
